export const listData = [
    {
      id: 1,
      title: "Shop Space Measuring 12 Sqm",
      img: ["/images/bg.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      // description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 8000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 2,
      title: "Shop Space Measuring 16 Sqm",
      img: ["/images/bg8.jpg"],
      images: [
        "/images/bg9.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: "Bright, spacious, and strategically located. This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",
      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 14000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 3,
      title: "Shop Space Measuring 20 Sqm",
      img: ["/images/bg10.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 22000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 4,
      title: "Shop Space Measuring 60 Sqm",
      img: ["/images/bg12.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 40000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 5,
      title: "Shop Space Measuring 35 Sqm",
      img: ["/images/bg11.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 2000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 6,
      title: "Shop Space Measuring 50 Sqm",
      img: ["/images/bg2.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 4000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 7,
      title: "Shop Space Measuring 2 Sqm",
      img: ["/images/bg14.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 2000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 8,
      title: "Shop Space Measuring 60 Sqm",
      img: ["/images/bg.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 40000000,
      address: "Ariaria aba", 
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 1,
      title: "Shop Space Measuring 12 Sqm",
      img: ["/images/bg.jpg"],
      images: [
        "/images/bg7.jpg",
        "/images/bg4.jpg",
        "/images/bg9.jpg",
        "/images/bg11.jpg",
        // "/images/bg1.jpg",
      ],
      // description: " This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",

      bedroom: 2,
      bathroom: 1,
      size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
      price: 8000000,
      address: "Ariaria aba A-Line rd",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    // {
    //   id: 2,
    //   title: "Shop Space Measuring 16 Sqm",
    //   img: ["/images/bg8.jpg"],
    //   images: [
    //     "/images/bg9.jpg",
    //     "/images/bg4.jpg",
    //     "/images/bg9.jpg",
    //     "/images/bg11.jpg",
    //     // "/images/bg1.jpg",
    //   ],
    //   description: "Bright, spacious, and strategically located. This shop features high foot traffic, large display windows, and flexible interior layout — perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility.",
    //   bedroom: 2,
    //   bathroom: 1,
    //   size: 861,
    // latitude: 51.5074,
    // longitude: -0.1278,
    //   price: 14000000,
    //   address: "Airiara aba",
    //   latitude: 51.5074,
    //   longitude: -0.1278,
    // },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Shop Space Measuring 2 Sqm",
    price: 2000000,
    images: [
      "http://localhost:5173/images/bg.jpg",
      "http://localhost:5173/images/bg11.jpg",
      "http://localhost:5173/images/bg2.jpg",
      "http://localhost:5173/images/bg10.jpg",
    ],
    bedRooms: 2,
    bathroom: 1,
    // details: "Serviced",
    // details: "Serviced",
    latitude: 5.1066,
    longitude: 7.3667,    
    city: "Aba",
    address: "Faulks Road Aba",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description: "A 2sqm shop space: This shop features high foot traffic, large display windows, and flexible interior layout perfect for retail, service-based businesses, or boutique showrooms. Secure environment, ample parking, and strong local visibility." ,
  };

  
  
  export const userData = {
    id: 1,
    name: "John Doe",
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  };